asyncagile/asyncagile/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'asyncagile.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('poker.urls')),
)

asyncagile/poker/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from poker.views.estimate import EstimateNew
from poker.views.project import ProjectDetails
from poker.views.story import StoryBrowse, StoryDetails

urlpatterns = patterns('',
    url(r'project/details/(?P<pk>[-_\w]+)',  login_required(ProjectDetails.as_view()), name='project-details'),
    url(r'story/browse/$',  login_required(StoryBrowse.as_view()), name='story-browse'),
    url(r'story/details/(?P<pk>[-_\w]+)',  login_required(StoryDetails.as_view()), name='story-details'),
    url(r'estimate/new/(?P<story>\w+)',  login_required(EstimateNew.as_view()), name='estimate-new'),
)

asyncagile/poker/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    moderator = models.ForeignKey(User, related_name='+')
    name      = models.CharField(max_length=32)
    members   = models.ManyToManyField(User, blank=True, null=True)

    def __unicode__(self):
        return self.name


class Story(models.Model):
    project     = models.ForeignKey(Project)
    title       = models.CharField(max_length=128)
    description = models.CharField(max_length=255, null=True, blank=True)
    created_at  = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def get_estimated_by(self):
        return [e.user for e in self.estimate_set.all()]

    def __unicode__(self):
        return self.title


class Estimate(models.Model):
    story       = models.ForeignKey(Story)
    user        = models.ForeignKey(User)
    points      = models.SmallIntegerField()
    comment     = models.CharField(max_length=255, null=True, blank=True)
    created_at  = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

asyncagile/poker/views/estimate.py
from django.views.generic import TemplateView
from poker.models import Story, Estimate

class EstimateNew(TemplateView):
    template_name = 'estimate/new.html'

    def get_context_data(self, **kwargs):
        context = super(EstimateNew, self).get_context_data(**kwargs)
        story = Story.objects.get(pk=kwargs['story'])
        estimate = Estimate.objects.filter(user=self.request.user).filter(story=story)
        if estimate:
            # redirect
            print "yes"

        context['story'] = story

        return context

asyncagile/poker/views/project.py
from django.views.generic import DetailView
from poker.models import Project

class ProjectDetails(DetailView):
    template_name = 'project/details.html'
    model = Project
    context_object_name = 'project'

asyncagile/poker/views/story.py
from django.views.generic import TemplateView, DetailView
from poker.models import Story

class StoryBrowse(TemplateView):
    template_name = 'story/browse.html'


class StoryDetails(DetailView):
    model = Story
    context_object_name = 'story'
    template_name = 'story/details.html'

asyncagile/poker/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title>{% block title %}AsyncAgile - Poker{% endblock title %}</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block head_meta %}{% endblock head_meta %}

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    {% block head_css %}{% endblock head_css %}

    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

    {% block head_js %}{% endblock head_js %}

</head>

<body>

    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            <a class="navbar-brand" href="#">Planning Poker</a>
            </div>
        </div>
    </div>


    <!-- Content Pane -->
    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    {% block body_js %}{% endblock body_js %}
</body>

asyncagile/poker/templates/estimate/new.html
{% extends "base.html" %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="{%url 'project-details' story.project.pk %}">{{story.project.name}}</a></li>
  <li><a href="{%url 'story-details' story.pk %}">{{story.title}}</a></li>
  <li class="active">Estimate</li>
</ol>

<div>
    <h1>{{story.title}}</h1>

    <p class="lead">
        {{story.description}}
    </p>

    <h2>Estimate</h2>
    <div>
        <a href="#" class="btn btn-default btn-lg" role="button">1</a>
        <a href="#" class="btn btn-default btn-lg" role="button">2</a>
        <a href="#" class="btn btn-default btn-lg" role="button">3</a>
        <a href="#" class="btn btn-default btn-lg" role="button">5</a>
        <a href="#" class="btn btn-default btn-lg" role="button">8</a>
        <a href="#" class="btn btn-default btn-lg" role="button">13</a>
        <a href="#" class="btn btn-default btn-lg" role="button">20</a>
        <a href="#" class="btn btn-default btn-lg" role="button">40</a>
        <a href="#" class="btn btn-default btn-lg" role="button">100</a>
        <a href="#" class="btn btn-default btn-lg" role="button">?</a>
        <a href="#" class="btn btn-default btn-lg" role="button"><i class="fa fa-coffee"></i></a>
    </div>
</div>
{% endblock %}

asyncagile/poker/templates/project/details.html
{% extends "base.html" %}

{% block content %}
<ol class="breadcrumb">
  <li class="active">{{project.name}}</li>
</ol>
<div>
    <h1>Project: {{project.name}}</h1>

    <h2>Members</h2>
    <div>
        {% include "user/user-list.html" with users=project.members.all only %}
    </div>

    <h2>Active Stories</h2>
    <div>
        {% for story in project.story_set.all %}
            <p class="lead"><a href="{% url 'story-details' story.pk %}">{{story.title}}</a></p>
        {% empty %}
            <i>This project has no stories</i>
        {% endfor %}
    </div>


</div>
{% endblock %}

asyncagile/poker/templates/story/browse.html
{% extends "base.html" %}

{% block content %}
<h1>Browse Stories</h1>


{% endblock %}

asyncagile/poker/templates/story/details.html
{% extends "base.html" %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="{%url 'project-details' story.project.pk %}">{{story.project.name}}</a></li>
  <li class="active">{{story.title}}</li>
</ol>

<div>
    <h1>{{story.title}}</h1>

    <p class="lead">
        {{story.description}}
    </p>

    <br>

    <h2>Estimated By</h2>
    <div>
        {% include "user/user-list.html" with users=story.get_estimated_by only %}
    </div>

    <h2>Estimations</h2>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Points</th>
                <th>Comment</th>
            </tr>
        </thead>
    <tbody>
        {% for estimate in story.estimate_set.all %}
            <tr>
                <td>{{estimate.user.first_name}} {{estimate.user.last_name}}</td>
                <td>{{estimate.points}}</td>
                <td>{{estimate.comment}}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>

    <hr>

    <a href="{% url 'estimate-new' story.pk %}" class="btn btn-primary">Estimate</a>

</div>
{% endblock %}

asyncagile/poker/templates/user/user-list.html
{% for user in users %}
    {% include "user/user.html" with user=user only %}
{% empty %}
    <i>No users yet!</i>
{% endfor %}

asyncagile/poker/templates/user/user.html
{% load gravatar %}
<img src="{% gravatar_url user.email 80 %}" class="img-circle" alt="{{user.first_name}} {{user.last_name}}">